include:
  - project: 'datacluster/gitlab-templates'
    file: 'base-template.yml'
  - project: 'datacluster/gitlab-templates'
    file: 'push-chart-template.yml'

stages:
  - push

push-chart:
  extends: .push-chart-template
  stage: push
  script:
    - push
  only:
    refs:
      - tags
