name: Charts CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'      

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Add charts' dependency repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Helm lint
        working-directory: ./charts
        run: |
          helm lint helmet

      - name: Configure Git
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        if: ${{ github.event_name != 'pull_request' }}
        uses: helm/chart-releaser-action@v1.4.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

